INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(1, 'Living Room', 1);
INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(2, 'Bed Room', 1);
INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(3, 'Bath Room', 1);
INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(4, 'Kitchen', 1);
INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(5, 'WC', 2);
INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(6, 'Kids Room1', 2);
INSERT INTO ROOM(ID, NAME, FLOOR) VALUES(7, 'Kids Room2', 2);



INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (1, 8, 'ON', 1);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (2, 0, 'ON', 1);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (3, 9, 'ON', 2);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (4, 2, 'OFF', 2);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (5, 5, 'ON', 3);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (6, 0, 'OFF', 4);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (7, 0, 'ON', 5);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (8, 0, 'OFF', 6);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (9, 6, 'ON', 7);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (10, 0, 'OFF', 7);


